baseURL = "/"
languageCode = "en-us"
title = "NorthPacific Consulting"
theme = "kube"
description = "Melbourne based consulting team. Works on DevOps, Automation, Data Analytics and Proof-Of-Concepts development. Startups, Small and Medium sized organizations can contact us to get work done" 
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "northpacific" # add your company name
  github = "" # add your github profile name
  twitter = "northpacific_au" # add your twitter profile
  email = "info@northpacific.com.au"

[[menu.main]]
    name = "About"
    weight = -100
    url = "/company/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
